version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:12.18.4
        auth:
          username: ampify
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Publish to focusrite-novation registry
          command: node bump.js "@focusrite-novation/ampify-prettier-config" "1.1.$CIRCLE_BUILD_NUM" && publish
      - run:
          name: Publish to focusritegroup registry
          command: node bump.js "@focusritegroup/ampify-prettier-config" "1.1.$CIRCLE_BUILD_NUM" && npm publish

workflows:
  publish:
    jobs:
      - publish:
          context:
            - NPM-CONFIG
            - DOCKER_HUB
          filters:
            branches:
              only:
                - master
